_GPL.j(function(n){!function(c,U,V,g,f,ca,da,Xa,Ya,h,ya,ea,fa,Za,za,$a,ga,Aa,ab,bb,Ba,Ca,cb,db,eb,fb,Da,gb,Ea,Fa,hb,ib,z,Ga,J,ha,Ha,jb,Ia,kb,Ja,ia,Ka,lb,mb,La,nb,Ma,r,p,W,ob,s,Na,Oa){function K(){L(t,J,K);Pa(function(a,b){d=a;M||(M=!0,Qa(),X(),N(t,J,X),ja=ea(function(){36E5<+new g-ka&&Y(!1)},5E3))})}function X(){ka=+new g}function Y(a){if(M){M=!1;U(ja);Z=!1;L(la,O,P);for(var b=t.getElementsByTagName("a"),e=0;e<b.length;++e)L(b[e],O,P);L(t,J,X);a||N(t,J,K)}}function N(a,b,e){if(k[ga])a[ga](b,e,!1);
else a[Aa](ha+b,e)}function Qa(){Z=!0;N(la,O,P);for(var a=t.getElementsByTagName("a"),b=0;b<a.length;++b)N(a[b],O,P)}function Q(a){a=k[Ja][Ma][La]().match(ya(a+"[/ ](\\d+)","i"));return h(a&&a[1],10)}function ma(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var b=[];n("title").length&&(b=b.concat(a(n("title").text())));n('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var e=n.trim(n(this).attr("content"));
e&&e.match(/^\s*[a-zA-Z0-9]/)&&(b=b.concat(a(e)))});return n.trim(function(a){var b=[];n.each(a,function(a,e){-1==n.inArray(e,b)&&b.push(e)});return b}(b).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function na(){var a=k[z].href.substr(0,1500),b="/"!=k[z].pathname?ma():"",a=a.replace(/:/g,"%3A"),b=b.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),e=c.getSubId?"&subid="+c.getSubId("z7b85"):"",a=f(c.B64.encode(a+"::z-"+G+"-"+Sa+"::"+b));return c.proto+oa+"/pops?c="+a+"&a=1&ch="+
f(H)+e}function L(a,b,e){if(k[ia])a[ia](b,e,!1);else a[Da](ha+b,e)}function Ta(a){a=a||window.event||{};if(1<a.which||0<a.button)return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function A(a,b){a=h(a,10);isNaN(a)&&(a=h(R&&R.getItem(b)||c.gc(b,10),10)||0);return a}function S(){u=h(u,10)||0;l=h(l,10)||0;x=h(x,10)||0;var a=v(),b=l&&(new g(1E3*u)).getDate()!=(new g(1E3*a)).getDate();b&&(l=0);var e=!B||a-u>=C&&l<B,a=a-x>=w;return!m&&b||e&&a}function P(a){if(!Ta(a)){var b;
if(b=Z)if(q.swf?(u=A(q.get(r),r),316808>pa.score&&(l=A(q.get(s),s)),b=qa(q.get(p)),x=A(b[E],p),b=S()):b=!0,b){if(!m){a=a.target||a.srcElement;for(b="";a;){F||(F=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){b=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}b&&(d+="&t="+f(b.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new g-ra);F&&(d+="&data_tag="+f(F));"/"!=k[z].pathname&&(d+="&mk="+f(c.B64.encode(ma().substring(0,Math.max(0,1500-d.length)))))}c.log("Popping to: "+
d);a="ld893_"+(I?"_"+f(I)+"_":"")+"_"+v();b=k[Ha](c.proto+c.baseCDN+"/pwn.html?u="+f(d)+"&n="+a+"&r=","_blank")}($=b)&&!$.closed&&(Y(!0),a=v(),sa(r,C,a),q.set(Na,a),u=a,q.set(s,++l),w&&sa(p,w,T+(T&&",")+E+":"+a),m||Ua($))}}function Ua(a){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popwinopen_new&u="+f(d)+"&location="+f(k[z].hostname)+"&pid="+G+"&tag="+f(F||"")+"&r="+999999999*Math.random();var b=+new g,e=ea(function(){var c=+new g-b;if(5E3<=c)U(e);else if(a.closed||!1!==a.closed)U(e),(new Image).src=
"//cdnstats-a.akamaihd.net/s.gif?t=popwinclosed_new&u="+f(d)+"&location="+f(k[z].hostname)+"&pid="+G+"&tag="+f(F||"")+"&delay="+c+"&r="+999999999*Math.random()},200)}function v(){return ca(new g/1E3)}function sa(a,b,e){q.set(a,e);e=v();R&&R.setItem(a,e);b=h(b);var c=new g;c.setSeconds(c.getSeconds()+b);t.cookie=a+"="+e+";expires="+c.toUTCString()+";path=/;domain="+E}function qa(a){var b={},e=v(),c=[];a=(a||"").split(",");if(a.length){for(var f=0;f<a.length;++f){var d=a[f].split(":"),g=h(d[1],10);
e-g<w&&(b[d[0]]=g,c.push(d[0]+":"+g))}T=c.join(",");q.set(p,T)}return b}function ta(){return S()?1:v()-(h(x,10)||0)<w?Infinity:l>=B?"US"==c.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?88620:59858:"US"==c.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?59858:49928}function Va(a){"US"==c.vars.cid?aa(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(c.vars.cid)?aa(a,59858,88620):aa(a,49928,59858);return S()}function aa(a,b,c){a>=b&&(C=0,a>=c&&l>=B&&(l=da(0,
l-1)))}function Pa(a){var b="http://secure.xsrving.com/display?size=800x600&ch="+f(H)+"&referer="+f(E);c.items.z7b85={callback:function(b){I="";if(b)if(b.score==za)c.sc(W,v(),6,k[z].hostname);else{b.cid&&(I=b.cid,b.url||(b.url=c.proto+oa+"/click?c="+f(I)+(c.getSubId?"&subid="+c.getSubId("z7b85"):"")+(ua?"&data_test="+f(ua):"")));var d=h(b.score,10);if(m||0<d&&Va(d))m||(ra=+new g,V(ba),b.url&&b.expires&&(V(va),va=fa(function(){Y(!0);K()},1E3*h(b.expires,10)))),pa={score:d,now:new g/1},a(b.url,d)}}};
!function Ra(){c.gc(W)||q.get(["frt","_GPL_oo_z7b85",r,p,s,Oa],function(d){if(d.v.frt){if("1750"==G){var f=h(d.v._GPL_oo_z7b85,10)||0;if(86400>ca(new g/1E3)-f)return}f=v();u=A(d.v[r],r);l=A(d.v[s],s);d=qa(d.v[p]);x=A(d[E],p);S()?m?a(b,0):c.insertJS(na()+"&ms="+ta()+"&r="+f):m||(d=ta(),c.log("minScoreNeeded: "+d),Infinity>d&&!wa&&(c.insertJS(na()+"&ms="+d+"&r="+f),wa=!0),V(ba),ba=fa(Ra,1E3*(5+da(f,u+C,x+w)-f)))}})}()}var q=c.items.e6a00,k=window,t=k.document,la=t.body,R=k.localStorage,Wa=Q(Ba);Q(Fa);
Q(Ia);Q(Ka);var H=c.item_vars["22555_ch"]||c.item_vars.ch||"",C,u,x,y=c.dt(),y=y&&y.inherited&&y.inherited.t||[],m="x"==H||-1<y.indexOf("adult")||0==y.length&&0<n('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;m&&(-1==y.indexOf("adult_block")?H="x":(H="x-issue",m=!1));var w,oa="p.display-trk.com",M=!1,ja,ka,Z=!1,E=c.gd(),d,$,ra=0,va,T="",l=0,B,pa={},I="",ba,wa=!1,ua,F,O=Wa?Ga+Ea:Ca,xa=c.zoneid("z7b85",!0).split("_"),Sa=xa[0],G=xa[1]||c.vars.pid;c.canLoad("ld893")||c.gc(W)||m&&!c.canLoad("i4c62")||
(window.name||"").match(/^a652c_/)||1797==G&&"GB"==c.vars.cid||"facebook.com"==E||(m?(B=C=0,w=180,r+="_xr",p+="_xr",s+="_xr"):(C=360,B=4,w=360),K())}(_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,Math.floor,Math.max,Math.random,null,parseInt,RegExp,setInterval,setTimeout,String,void 0,"about","addEventListener","attachEvent","blank","blur","chrome","click","client","close","javascript:window.close()","contentDocument","detachEvent","dialog","down","firefox","focus","load","location","mouse",
"mousemove","on","open","opener","opera","over","navigator","removeEventListener","safari","screen","showModalDialog","toLowerCase","up","userAgent","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test")});
